package export

import (
	"fmt"
	"path/filepath"
	"strings"
)

type EnemySkillFunction struct {
	ID             string
	Body           string
	DispatcherLine string
}

func BuildEnemySkillArtifacts(master DBMaster, skillLogicalDir string) []EnemySkillFunction {
	if master == nil {
		return []EnemySkillFunction{}
	}

	entries := master.ListEnemySkills()
	out := make([]EnemySkillFunction, 0, len(entries))
	for _, entry := range entries {
		out = append(out, EnemySkillFunction{
			ID:             entry.ID,
			Body:           entry.Script,
			DispatcherLine: fmt.Sprintf("execute if entity @s[tag=%s] run function %s", entry.ID, functionRefName(skillLogicalDir, entry.ID)),
		})
	}
	return out
}

func WriteEnemySkillArtifacts(skillDir string, skills []EnemySkillFunction) error {
	dispatchLines := []string{"# generated by maf-command-editor: enemy skill dispatcher"}
	for _, entry := range skills {
		path := filepath.Join(skillDir, entry.ID+".mcfunction")
		if err := writeFunctionFile(path, entry.Body); err != nil {
			return err
		}
		dispatchLines = append(dispatchLines, entry.DispatcherLine)
	}
	if len(skills) == 0 {
		dispatchLines = append(dispatchLines, "# no enemy skill entries")
	}

	mainPath := filepath.Join(skillDir, "main.mcfunction")
	return writeFunctionFile(mainPath, strings.Join(dispatchLines, "\n"))
}
