package export

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	spawntableModel "maf_command_editor/app/domain/model/spawntable"
)

type SpawnTableArtifact struct {
	ID        string
	Table     string
	MainEntry string
}

func BuildSpawnTableArtifacts(dmas DBMaster, replaceLogicalDir, enemyLogicalDir string) []SpawnTableArtifact {
	if dmas == nil {
		return []SpawnTableArtifact{}
	}

	tables := dmas.ListSpawnTables()
	artifacts := make([]SpawnTableArtifact, 0, len(tables))
	for _, table := range tables {
		artifacts = append(artifacts, buildSpawnTableArtifact(table, replaceLogicalDir, enemyLogicalDir))
	}
	return artifacts
}

func WriteSpawnTableArtifacts(dir string, artifacts []SpawnTableArtifact) error {
	mainLines := []string{"# generated by maf-command-generator: spawn table dispatcher"}
	for _, entry := range artifacts {
		path := filepath.Join(dir, entry.ID+".mcfunction")
		if err := writeFunctionFile(path, entry.Table); err != nil {
			return err
		}
		mainLines = append(mainLines, entry.MainEntry)
	}
	if len(artifacts) == 0 {
		mainLines = append(mainLines, "# no spawn table entries")
	}

	return writeFunctionFile(filepath.Join(dir, "main.mcfunction"), strings.Join(mainLines, "\n"))
}

func buildSpawnTableArtifact(table spawntableModel.SpawnTable, replaceLogicalDir, enemyLogicalDir string) SpawnTableArtifact {
	totalWeight := table.GetBaseMobWeight()
	for _, replacement := range table.Replacements {
		totalWeight += replacement.Weight
	}

	bodyLines := []string{
		fmt.Sprintf("# generated by maf-command-generator: spawn table %s", table.ID),
		fmt.Sprintf("execute store result score @s maf_vh_rand run random value 1..%d", totalWeight),
	}

	replaceWeight := 0
	for _, replacement := range table.Replacements {
		start := replaceWeight + 1
		replaceWeight += replacement.Weight
		bodyLines = append(bodyLines, fmt.Sprintf(
			"execute if score @s maf_vh_rand matches %d..%d run function %s",
			start,
			replaceWeight,
			functionRefName(enemyLogicalDir, replacement.EnemyID),
		))
	}

	bodyLines = append(bodyLines, fmt.Sprintf(
		"execute if score @s maf_vh_rand matches 1..%d run function maf:killme",
		replaceWeight,
	))
	baseStart := replaceWeight + 1
	if baseMergeNBT, ok := baseMobMergeNBT(table.GetBaseMobAttributes()); ok && baseStart <= totalWeight {
		bodyLines = append(bodyLines, fmt.Sprintf(
			"execute if score @s maf_vh_rand matches %d..%d run data merge entity @s %s",
			baseStart,
			totalWeight,
			baseMergeNBT,
		))
	}

	dx := table.MaxX - table.MinX
	dy := table.MaxY - table.MinY
	dz := table.MaxZ - table.MinZ

	return SpawnTableArtifact{
		ID:    table.ID,
		Table: strings.Join(bodyLines, "\n"),
		MainEntry: fmt.Sprintf(
			"execute if dimension %s if entity @s[x=0,y=100,z=0,distance=%d..%d] if entity @s[x=%d,y=%d,z=%d,dx=%d,dy=%d,dz=%d,type=%s] run function %s",
			table.Dimension,
			table.MinDistance,
			table.MaxDistance,
			table.MinX,
			table.MinY,
			table.MinZ,
			dx,
			dy,
			dz,
			table.SourceMobType,
			functionRefName(replaceLogicalDir, table.ID),
		),
	}
}
func baseMobMergeNBT(attrs *spawntableModel.BaseMobAttributes) (string, bool) {
	if attrs == nil {
		return "", false
	}

	parts := make([]string, 0, 2)
	attributeValues := make([]string, 0, 4)
	if attrs.HP != nil {
		value := formatNBTFloat(*attrs.HP)
		parts = append(parts, fmt.Sprintf("Health:%sf", value))
		attributeValues = append(attributeValues, fmt.Sprintf("{Name:generic.max_health,Base:%s}", value))
	}
	if attrs.Attack != nil {
		attributeValues = append(attributeValues, fmt.Sprintf("{Name:generic.attack_damage,Base:%s}", formatNBTFloat(*attrs.Attack)))
	}
	if attrs.Defense != nil {
		attributeValues = append(attributeValues, fmt.Sprintf("{Name:generic.armor,Base:%s}", formatNBTFloat(*attrs.Defense)))
	}
	if attrs.MoveSpeed != nil {
		attributeValues = append(attributeValues, fmt.Sprintf("{Name:generic.movement_speed,Base:%s}", formatNBTFloat(*attrs.MoveSpeed)))
	}
	if len(attributeValues) > 0 {
		parts = append(parts, fmt.Sprintf("Attributes:[%s]", strings.Join(attributeValues, ",")))
	}
	if len(parts) == 0 {
		return "", false
	}
	return "{" + strings.Join(parts, ",") + "}", true
}

func formatNBTFloat(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}
