package export

import (
	"fmt"
	"path/filepath"
	"strings"

	spawntableModel "maf_command_editor/app/domain/model/spawntable"
)

type SpawnTableArtifact struct {
	ID        string
	Table     string
	MainEntry string
}

func BuildSpawnTableArtifacts(dmas DBMaster, replaceLogicalDir, enemyLogicalDir string) []SpawnTableArtifact {
	if dmas == nil {
		return []SpawnTableArtifact{}
	}

	tables := dmas.ListSpawnTables()
	artifacts := make([]SpawnTableArtifact, 0, len(tables))
	for _, table := range tables {
		artifacts = append(artifacts, buildSpawnTableArtifact(table, replaceLogicalDir, enemyLogicalDir))
	}
	return artifacts
}

func WriteSpawnTableArtifacts(dir string, artifacts []SpawnTableArtifact) error {
	mainLines := []string{"# generated by maf-command-generator: spawn table dispatcher"}
	for _, entry := range artifacts {
		path := filepath.Join(dir, entry.ID+".mcfunction")
		if err := writeFunctionFile(path, entry.Table); err != nil {
			return err
		}
		mainLines = append(mainLines, entry.MainEntry)
	}
	if len(artifacts) == 0 {
		mainLines = append(mainLines, "# no spawn table entries")
	}

	return writeFunctionFile(filepath.Join(dir, "main.mcfunction"), strings.Join(mainLines, "\n"))
}

func buildSpawnTableArtifact(table spawntableModel.SpawnTable, replaceLogicalDir, enemyLogicalDir string) SpawnTableArtifact {
	totalWeight := table.BaseMobWeight
	for _, replacement := range table.Replacements {
		totalWeight += replacement.Weight
	}

	bodyLines := []string{
		fmt.Sprintf("# generated by maf-command-generator: spawn table %s", table.ID),
		fmt.Sprintf("execute store result score @s maf_vh_rand run random value 1..%d", totalWeight),
	}

	replaceWeight := 0
	for _, replacement := range table.Replacements {
		start := replaceWeight + 1
		replaceWeight += replacement.Weight
		bodyLines = append(bodyLines, fmt.Sprintf(
			"execute if score @s maf_vh_rand matches %d..%d run function %s",
			start,
			replaceWeight,
			functionRefName(enemyLogicalDir, replacement.EnemyID),
		))
	}

	bodyLines = append(bodyLines, fmt.Sprintf(
		"execute if score @s maf_vh_rand matches 1..%d run function maf:killme",
		replaceWeight,
	))

	dx := table.MaxX - table.MinX
	dy := table.MaxY - table.MinY
	dz := table.MaxZ - table.MinZ

	return SpawnTableArtifact{
		ID:    table.ID,
		Table: strings.Join(bodyLines, "\n"),
		MainEntry: fmt.Sprintf(
			"execute if dimension %s if entity @s[x=0,y=100,z=0,distance=%d..%d] if entity @s[x=%d,y=%d,z=%d,dx=%d,dy=%d,dz=%d,type=%s] run function %s",
			table.Dimension,
			table.MinDistance,
			table.MaxDistance,
			table.MinX,
			table.MinY,
			table.MinZ,
			dx,
			dy,
			dz,
			table.SourceMobType,
			functionRefName(replaceLogicalDir, table.ID),
		),
	}
}
