# generated by maf-command-generator: spawn table dispatcher
execute if dimension minecraft:overworld if entity @s[x=0,y=100,z=0,distance=0..1000] if entity @s[x=-100,y=-64,z=-100,dx=200,dy=384,dz=200,type=minecraft:zombie] run function maf:generated/enemy/replace/overworld_zombies
