# generated by maf-command-generator: spawn table overworld_zombies
execute store result score @s maf_vh_rand run random value 1..100
execute if score @s maf_vh_rand matches 1..30 run function maf:generated/enemy/spawn/enemy_1
execute if score @s maf_vh_rand matches 31..70 run function maf:generated/enemy/spawn/enemy_2
execute if score @s maf_vh_rand matches 1..70 run function maf:killme
