# generated by maf-command-generator: spawn table overworld_zombies_attributes
execute store result score @s maf_vh_rand run random value 1..100
execute if score @s maf_vh_rand matches 1..30 run function maf:generated/enemy/spawn/enemy_1
execute if score @s maf_vh_rand matches 31..70 run function maf:generated/enemy/spawn/enemy_2
execute if score @s maf_vh_rand matches 1..70 run function maf:killme
execute if score @s maf_vh_rand matches 71..100 run data merge entity @s {Health:100f,Attributes:[{Name:generic.max_health,Base:100},{Name:generic.attack_damage,Base:6},{Name:generic.armor,Base:2},{Name:generic.movement_speed,Base:0.22}]}
