package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"maf-command-editor/app/internal/domain/entity/enemyskills"
	"maf-command-editor/app/internal/domain/entity/grimoire"
	"maf-command-editor/app/internal/domain/entity/items"
	"maf-command-editor/app/internal/domain/entity/skills"
)

func generateItemOutputs(settings ExportSettings, entries []items.ItemEntry) (itemOutputStats, error) {
	functionRoot := filepath.Join(settings.OutputRoot, settings.Paths.ItemFunctionDir)
	lootRoot := filepath.Join(settings.OutputRoot, settings.Paths.ItemLootDir)
	if err := os.MkdirAll(functionRoot, 0o755); err != nil {
		return itemOutputStats{}, err
	}
	if err := os.MkdirAll(lootRoot, 0o755); err != nil {
		return itemOutputStats{}, err
	}
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(functionRoot, entry.ID+".mcfunction"), []byte(strings.Join([]string{
			fmt.Sprintf("# itemId=%s sourceId=%s", entry.ItemID, entry.ID),
			fmt.Sprintf("loot give @s loot %s", lootTableResourceID(settings, settings.Paths.ItemLootDir, entry.ID)),
			"",
		}, "\n")), 0o644); err != nil {
			return itemOutputStats{}, err
		}
		if err := writeJSON(filepath.Join(lootRoot, entry.ID+".json"), toItemLootTable(entry)); err != nil {
			return itemOutputStats{}, err
		}
	}
	return itemOutputStats{ItemFunctions: len(entries), ItemLootTables: len(entries)}, nil
}

func generateGrimoireOutputs(settings ExportSettings, entries []grimoire.GrimoireEntry) (spellOutputStats, error) {
	functionRoot := filepath.Join(settings.OutputRoot, settings.Paths.SpellFunctionDir)
	lootRoot := filepath.Join(settings.OutputRoot, settings.Paths.SpellLootDir)
	if err := os.MkdirAll(functionRoot, 0o755); err != nil {
		return spellOutputStats{}, err
	}
	if err := os.MkdirAll(lootRoot, 0o755); err != nil {
		return spellOutputStats{}, err
	}

	dispatchLines := make([]string, 0, len(entries))
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(functionRoot, entry.ID+".mcfunction"), []byte(normalizeFunctionBody(entry.Script)), 0o644); err != nil {
			return spellOutputStats{}, err
		}
		if err := writeJSON(filepath.Join(lootRoot, entry.ID+".json"), toSpellLootTable(entry)); err != nil {
			return spellOutputStats{}, err
		}
		dispatchLines = append(dispatchLines, fmt.Sprintf("execute if entity @s[scores={mafEffectID=%d}] run function %s", entry.CastID, functionResourceID(settings, settings.Paths.SpellFunctionDir, entry.ID)))
	}
	if err := os.WriteFile(filepath.Join(functionRoot, "selectexec.mcfunction"), []byte(strings.Join(dispatchLines, "\n")+"\n"), 0o644); err != nil {
		return spellOutputStats{}, err
	}
	return spellOutputStats{SpellFunctions: len(entries) + 1, SpellLootTables: len(entries)}, nil
}

func generateGrimoireDebugFunctions(settings ExportSettings, entries []grimoire.GrimoireEntry) (int, error) {
	root := filepath.Join(settings.OutputRoot, generatedGrimoireDebugFunctionDir(settings))
	if err := os.MkdirAll(root, 0o755); err != nil {
		return 0, err
	}
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(root, entry.ID+".mcfunction"), []byte(grimoireDebugGiveCommand(entry)+"\n"), 0o644); err != nil {
			return 0, err
		}
	}
	return len(entries), nil
}

func generateSkillOutputs(settings ExportSettings, entries []skills.SkillEntry) (skillOutputStats, error) {
	root := filepath.Join(settings.OutputRoot, settings.Paths.SkillFunctionDir)
	if err := os.MkdirAll(root, 0o755); err != nil {
		return skillOutputStats{}, err
	}
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(root, entry.ID+".mcfunction"), []byte(normalizeFunctionBody(entry.Script)), 0o644); err != nil {
			return skillOutputStats{}, err
		}
	}
	return skillOutputStats{SkillFunctions: len(entries)}, nil
}

func generateEnemySkillOutputs(settings ExportSettings, entries []enemyskills.EnemySkillEntry) (enemySkillOutputStats, error) {
	root := filepath.Join(settings.OutputRoot, settings.Paths.EnemySkillFunctionDir)
	if err := os.MkdirAll(root, 0o755); err != nil {
		return enemySkillOutputStats{}, err
	}
	dispatchLines := []string{"# generated by maf-command-editor: enemy skill dispatcher"}
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(root, entry.ID+".mcfunction"), []byte(normalizeFunctionBody(entry.Script)), 0o644); err != nil {
			return enemySkillOutputStats{}, err
		}
		dispatchLines = append(dispatchLines, fmt.Sprintf("execute if entity @s[tag=%s] run function %s", entry.ID, functionResourceID(settings, settings.Paths.EnemySkillFunctionDir, entry.ID)))
	}
	if len(entries) == 0 {
		dispatchLines = append(dispatchLines, "# no enemy skill entries")
	}
	if err := os.WriteFile(filepath.Join(root, "main.mcfunction"), []byte(strings.Join(dispatchLines, "\n")+"\n"), 0o644); err != nil {
		return enemySkillOutputStats{}, err
	}
	return enemySkillOutputStats{EnemySkillFunctions: len(entries) + 1}, nil
}
