package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"tools2/app/internal/domain/enemies"
	"tools2/app/internal/domain/grimoire"
	"tools2/app/internal/domain/items"
	"tools2/app/internal/domain/spawntables"
)

func generateSpawnTableOutputs(settings ExportSettings, entries []spawntables.SpawnTableEntry) (spawnTableOutputStats, error) {
	replacerRoot := filepath.Join(settings.OutputRoot, generatedVHReplacerFunctionDir(settings))
	ruleRoot := filepath.Join(settings.OutputRoot, generatedVHReplacerRuleFunctionDir(settings))
	if err := os.MkdirAll(replacerRoot, 0o755); err != nil {
		return spawnTableOutputStats{}, err
	}
	if err := os.MkdirAll(ruleRoot, 0o755); err != nil {
		return spawnTableOutputStats{}, err
	}

	tickLines := []string{"# generated by tools2: spawn replacement selector"}
	for _, entry := range entries {
		if err := os.WriteFile(filepath.Join(ruleRoot, entry.ID+".mcfunction"), []byte(strings.Join(spawnTableRuleLines(settings, entry), "\n")+"\n"), 0o644); err != nil {
			return spawnTableOutputStats{}, err
		}
		dx := entry.MaxX - entry.MinX
		dy := entry.MaxY - entry.MinY
		dz := entry.MaxZ - entry.MinZ
		tickLines = append(tickLines,
			fmt.Sprintf("execute if entity @s[type=%s] if dimension %s if entity @s[x=%d,y=%d,z=%d,dx=%d,dy=%d,dz=%d] run function %s",
				entry.SourceMobType,
				entry.Dimension,
				entry.MinX, entry.MinY, entry.MinZ,
				dx, dy, dz,
				functionResourceID(settings, generatedVHReplacerRuleFunctionDir(settings), entry.ID),
			),
		)
	}
	tickLines = append(tickLines, "tag @s add maf_vh_checked")
	tickPath := filepath.Join(replacerRoot, "tick.mcfunction")
	if err := os.WriteFile(tickPath, []byte(strings.Join(tickLines, "\n")+"\n"), 0o644); err != nil {
		return spawnTableOutputStats{}, err
	}

	return spawnTableOutputStats{SpawnTableFunctions: len(entries) + 1}, nil
}

func spawnTableRuleLines(settings ExportSettings, entry spawntables.SpawnTableEntry) []string {
	lines := []string{
		fmt.Sprintf("# spawn table %s source=%s dimension=%s", entry.ID, entry.SourceMobType, entry.Dimension),
	}
	totalWeight := entry.BaseMobWeight
	for _, replacement := range entry.Replacements {
		totalWeight += replacement.Weight
	}
	if totalWeight <= 0 {
		return append(lines, "tag @s add maf_vh_checked")
	}
	lines = append(lines, fmt.Sprintf("execute store result score rand p7_Rand1 run random value 0..%d", totalWeight-1))

	start := entry.BaseMobWeight
	for _, replacement := range entry.Replacements {
		end := start + replacement.Weight - 1
		if replacement.Weight > 0 {
			lines = append(lines,
				fmt.Sprintf("execute if score rand p7_Rand1 matches %d..%d at @s run function %s", start, end, functionResourceID(settings, settings.Paths.EnemyFunctionDir, replacement.EnemyID)),
				fmt.Sprintf("execute if score rand p7_Rand1 matches %d..%d run kill @s", start, end),
			)
		}
		start = end + 1
	}
	lines = append(lines, "tag @s add maf_vh_checked")
	return lines
}

func generateEnemyOutputs(settings ExportSettings, entries []enemies.EnemyEntry, itemEntries []items.ItemEntry, grimoireEntries []grimoire.GrimoireEntry) (enemyOutputStats, error) {
	functionRoot := filepath.Join(settings.OutputRoot, settings.Paths.EnemyFunctionDir)
	lootRoot := filepath.Join(settings.OutputRoot, settings.Paths.EnemyLootDir)
	if err := os.MkdirAll(functionRoot, 0o755); err != nil {
		return enemyOutputStats{}, err
	}
	if err := os.MkdirAll(lootRoot, 0o755); err != nil {
		return enemyOutputStats{}, err
	}

	itemsByID := map[string]items.ItemEntry{}
	for _, entry := range itemEntries {
		itemsByID[entry.ID] = entry
	}
	grimoiresByID := map[string]grimoire.GrimoireEntry{}
	for _, entry := range grimoireEntries {
		grimoiresByID[entry.ID] = entry
	}

	for _, entry := range entries {
		lootTable, err := buildDropLootTable(toTreasureDrops(entry.Drops), itemsByID, grimoiresByID, "enemy("+entry.ID+")")
		if err != nil {
			return enemyOutputStats{}, err
		}
		if err := writeJSON(filepath.Join(lootRoot, entry.ID+".json"), lootTable); err != nil {
			return enemyOutputStats{}, err
		}
		if err := os.WriteFile(filepath.Join(functionRoot, entry.ID+".mcfunction"), []byte(strings.Join(toEnemyFunctionLines(settings, entry, itemsByID), "\n")+"\n"), 0o644); err != nil {
			return enemyOutputStats{}, err
		}
	}
	return enemyOutputStats{EnemyFunctions: len(entries), EnemyLootTables: len(entries)}, nil
}
