package export

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func writeDatapackScaffold(settings ExportSettings) error {
	if err := os.MkdirAll(settings.OutputRoot, 0o755); err != nil {
		return err
	}

	outputDirs := []string{
		settings.Paths.ItemFunctionDir,
		settings.Paths.ItemLootDir,
		settings.Paths.SpellFunctionDir,
		settings.Paths.SpellLootDir,
		settings.Paths.SkillFunctionDir,
		settings.Paths.EnemySkillFunctionDir,
		settings.Paths.EnemyFunctionDir,
		settings.Paths.EnemyLootDir,
		settings.Paths.TreasureLootDir,
		settings.Paths.LoottableLootDir,
		generatedTickFunctionDir(settings),
		generatedGrimoireDebugFunctionDir(settings),
	}
	cleanupDirs := make([]string, 0, len(outputDirs))
	for _, relative := range outputDirs {
		if root, ok := generatedRootDir(relative); ok {
			cleanupDirs = append(cleanupDirs, root)
			continue
		}
		cleanupDirs = append(cleanupDirs, filepath.Clean(relative))
	}
	for _, relative := range uniqueSortedPaths(cleanupDirs) {
		abs := filepath.Join(settings.OutputRoot, relative)
		if err := os.RemoveAll(abs); err != nil {
			return err
		}
	}
	for _, relative := range uniqueSortedPaths(outputDirs) {
		abs := filepath.Join(settings.OutputRoot, relative)
		if err := os.MkdirAll(abs, 0o755); err != nil {
			return err
		}
	}
	return nil
}

func generatedRootDir(relative string) (string, bool) {
	normalized := filepath.ToSlash(filepath.Clean(relative))
	if normalized == "generated" || strings.HasSuffix(normalized, "/generated") {
		return filepath.FromSlash(normalized), true
	}
	if idx := strings.Index(normalized, "/generated/"); idx >= 0 {
		return filepath.FromSlash(normalized[:idx+len("/generated")]), true
	}
	return "", false
}

func uniqueSortedPaths(paths []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(paths))
	for _, path := range paths {
		normalized := filepath.Clean(path)
		if _, exists := seen[normalized]; exists {
			continue
		}
		seen[normalized] = struct{}{}
		out = append(out, normalized)
	}
	sort.Strings(out)
	return out
}

func generatedGrimoireDebugFunctionDir(settings ExportSettings) string {
	return filepath.Join("data", settings.Namespace, "function", "generated", "debug", "grimoire")
}

func generatedTickFunctionDir(settings ExportSettings) string {
	return filepath.Join("data", settings.Namespace, "function", "generated")
}

func generatedVHFunctionDir(settings ExportSettings) string {
	return filepath.Join(generatedTickFunctionDir(settings), "vh")
}

func generatedVHReplacerFunctionDir(settings ExportSettings) string {
	return filepath.Join(generatedVHFunctionDir(settings), "replacer")
}

func generatedVHReplacerRuleFunctionDir(settings ExportSettings) string {
	return filepath.Join(generatedVHReplacerFunctionDir(settings), "rule")
}

func generateTickDispatcher(settings ExportSettings) (int, error) {
	path := filepath.Join(settings.OutputRoot, generatedTickFunctionDir(settings), "tick.mcfunction")
	body := strings.Join([]string{
		"# generated by tools2: data-driven tick entrypoint",
		fmt.Sprintf("execute as @e[type=#p7b:enemymob,tag=!maf_vh_checked] at @s run function %s", functionResourceID(settings, generatedVHReplacerFunctionDir(settings), "tick")),
		fmt.Sprintf("execute as @e[tag=EnemySkill] at @s run function %s", functionResourceID(settings, settings.Paths.EnemySkillFunctionDir, "main")),
		"",
	}, "\n")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return 0, err
	}
	return 1, nil
}
